var bumens=[
    {
        bumenName:"办公室",
        bumenDescribe:"运筹帷幄",
        bumenNum:"1",
    },
    {
        bumenName:"教学部",
        bumenDescribe:"厚德载物",
        bumenNum:"3",
    },
    {
        bumenName:"财务部",
        bumenDescribe:"差之毫厘谬以千里",
        bumenNum:"1",
    },
    {
        bumenName:"安防部",
        bumenDescribe:"安全大于一切",
        bumenNum:"2",
    },
    {
        bumenName:"食堂",
        bumenDescribe:"民以食为天",
        bumenNum:"1",
    },
    {
        bumenName:"后勤部",
        bumenDescribe:"细节决定成败",
        bumenNum:"0",
    }
]