var pre=[
    {
        id:"111",
        pwd:"123456",
        limit:"teacher",
        userName:'张五',
        themeColor:'bule',
        headSrc:'../images/UI_01.png',
        myclassName:"小班",//班级名称
    },
    {
        id:"222",
        pwd:"123456",
        limit:"director",
        userName:'李园长',
        themeColor:'bule',
        headSrc:'../images/UI_02.png',
        myclassName:"all",//班级名称
    },
    {
        id:"333",
        pwd:"123456",
        limit:"administrator",
        userName:'管理员',
        themeColor:'bule',
        headSrc:'../images/UI_03.png',
        myclassName:"all",//班级名称
    }
];